; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "OxideSeeker"
#define MyAppVersion "2.0.0"
#define MyAppPublisher "严成"
#define MyAppURL "https://space.bilibili.com/253775617"
#define MyAppExeName "oxide_seeker.exe"
#define MyServiceName "OxideSeeker"
#define MyServiceExeName "oxide_seeker_service.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{3c53c98b-999d-4235-aac5-88f3dd5ea7c5}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\OxideSeeker
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=d:\Users\Documents
OutputBaseFilename=OxideSeeker_v{#MyAppVersion}
; 确保安装程序请求管理员权限
PrivilegesRequired=admin
SolidCompression=yes
WizardStyle=modern dynamic
; 如果检测到旧版本，默认使用之前的安装目录
UsePreviousAppDir=yes
; 安装包图标
SetupIconFile=D:\oxide_seeker\logo.ico

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"

[Tasks]
; 创建桌面快捷方式，默认勾选(不要加 Flags: unchecked，这样它就会默认勾选)
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"
; 开机启动，默认勾选
; Name: "autostart"; Description: "开机自动启动 {#MyAppName}"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
Source: "D:\oxide_seeker\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\oxide_seeker\{#MyServiceExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\oxide_seeker\config.toml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\oxide_seeker\dinov2_vits14_int8.onnx"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\oxide_seeker\onnxruntime.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\oxide_seeker\pdfium.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\oxide_seeker\ppocr_det.onnx"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\oxide_seeker\ppocr_rec.onnx"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Dirs]
; 关键在这里：赋予安装目录 Users 组修改权限
Name: "{app}"; Permissions: users-modify

[Icons]
; 将 {autoprograms} 改为 {commonprograms}，将 {autodesktop} 改为 {commondesktop}。

; --- 新增：指向前端页面的网页快捷方式 ---
; 开始菜单网页快捷方式
Name: "{commonprograms}\{#MyAppName}本地"; Filename: "http://localhost:7788"

; 桌面网页快捷方式 (受 desktopicon Task 控制)
Name: "{commondesktop}\{#MyAppName}"; Filename: "http://{computername}:7788"; Tasks: desktopicon
Name: "{commondesktop}\{#MyAppName}本地"; Filename: "http://localhost:7788"; Tasks: desktopicon

[Run]
; ShellExecute 代替 CreateProcess 来启动程序，因为只有 ShellExecute 能够识别 Manifest 清单并正确触发权限提升对话框（或继承安装程序的管理员权限）。
; 确保运行的程序也以管理员身份启动 在 [Run] 部分中，添加 runascurrentuser 标志
Filename: "{sys}\sc.exe"; Parameters: "create {#MyServiceName} start= auto binPath= ""{app}\{#MyServiceExeName}"" DisplayName= {#MyServiceName}"; Flags: runhidden
Filename: "{sys}\sc.exe"; Parameters: "description {#MyServiceName} OxideSeeker以图搜文件"; Flags: runhidden
Filename: "{sys}\sc.exe"; Parameters: "start {#MyServiceName}"; Flags: runhidden

; [Registry]
; 在 HKLM (所有用户) 或 HKCU (当前用户) 的 Run 项中添加
; Flags: uninsdeletevalue 表示卸载时删除该值
; Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; \
    ; ValueType: string; ValueName: "{#MyAppName}"; \
    ; ValueData: """cmd.exe"" /C start ""{app}\{#MyAppExeName}"""; \
    ; Flags: uninsdeletevalue; \
    ; Tasks: autostart

[UninstallDelete]
; Type: filesandordirs 表示同时删除文件和子目录
; Name: "{app}" 会尝试删除整个安装目录
; Type: filesandordirs; Name: "{app}"

[UninstallRun]
Filename: "{sys}\sc.exe"; Parameters: "stop {#MyServiceName}"; Flags: runhidden; RunOnceId: "StopService";
Filename: "{sys}\sc.exe"; Parameters: "delete {#MyServiceName}"; Flags: runhidden; RunOnceId: "DeleteService";
Filename: "cmd.exe"; Parameters: "/C taskkill /F /IM {#MyAppExeName} /IM nginx.exe"; Flags: runhidden; RunOnceId: "Taskkill";
Filename:"schtasks"; \
 Parameters:" /delete /f /tn ""{#MyServiceName}\AutoStart"; \
 RunOnceId: "DeleteAutoStart"; \
 Flags: runascurrentuser runhidden

[Code]
var
  IsUpdate: Boolean;       // 是否为升级安装
  OldInstallDir: String;   // 旧的安装路径

// 1. 辅助函数：通过注册表获取旧的安装路径
function GetOldInstallDir(): String;
var
  S: String;
begin
  Result := '';
  // 注意：这里的 GUID 必须和你 [Setup] 段中的 AppId 完全一致
  // 因为你配置了 64位模式，所以去 HKLM64 中寻找
  if RegQueryStringValue(HKLM64, 'Software\Microsoft\Windows\CurrentVersion\Uninstall\{3c53c98b-999d-4235-aac5-88f3dd5ea7c5}_is1', 'Inno Setup: App Path', S) then
    Result := S;
end;

// 2. 初始化阶段：仅做检测，不执行危险动作（避免报毒）
function InitializeSetup(): Boolean;
begin
  OldInstallDir := GetOldInstallDir();
  if OldInstallDir <> '' then
    IsUpdate := True
  else
    IsUpdate := False;
  Result := True;
end;

// 3. 决定是否跳过页面
function ShouldSkipPage(PageID: Integer): Boolean;
begin
  // 如果是升级安装，直接跳过目录选择页 (wpSelectDir)
  if IsUpdate and (PageID = wpSelectDir) then
    Result := True
  else
    Result := False;
end;

// 4. 封装关闭进程逻辑
procedure KillProcesses();
var
  ResultCode: Integer;
begin
  // 使用 cmd 调用 taskkill 减少杀毒软件误报
  // /f 表示强制，/im 表示进程映像名，SW_HIDE 隐藏黑窗口
  Exec('cmd.exe', '/c "taskkill /f /im {#MyAppExeName} /im {#MyServiceExeName}"', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Sleep(500); 
end;

