//! PP-OCR text extraction (detector + recognizer, ONNX via ort).
//!
//! Pure-Rust re-implementation of the RapidOCR pipeline for PP-OCRv3/v4
//! models — no Python, no new native dependencies; runs on the same ONNX
//! Runtime the vision encoder uses.
//!
//! * [`det`] — DBNet text detector: probability map → binarise → dilate →
//!   connected components → axis-aligned boxes with DB unclip expansion.
//!   Axis-aligned is a deliberate simplification: prepress artwork text is
//!   overwhelmingly horizontal, and rotated/curved display text is beyond
//!   the recognizer anyway.
//! * [`rec`] — CRNN/SVTR recognizer: 48-px-high strips → softmax over the
//!   6625-way vocabulary → greedy CTC decode.  The vocabulary ships inside
//!   the ONNX file's `character` metadata, so deployment stays two files.
//!
//! Sessions follow the same ownership model as `VisionSession`: one
//! [`OcrEngine`] per worker thread, `&mut self` inference.
//!
//! Reference parity is pinned by `test_fixtures/ocr_sample_expected.json`
//! (generated by RapidOCR-Python on the same image) via an `--ignored` test.

pub mod det;
pub mod rec;

use crate::error::{AppError, Result};
use image::DynamicImage;
use std::path::Path;

/// One recognised text line.
#[derive(Debug, Clone)]
pub struct OcrLine {
    pub text: String,
    /// Mean per-character CTC probability, `[0, 1]`.
    pub score: f32,
}

/// Minimum recognizer confidence for a line to be kept (RapidOCR default).
const TEXT_SCORE_MIN: f32 = 0.5;

/// Detector + recognizer pair.  Not `Sync`; give each worker its own.
pub struct OcrEngine {
    det: det::Detector,
    rec: rec::Recognizer,
}

impl OcrEngine {
    /// Load both models.  The recognizer's vocabulary is read from the ONNX
    /// `character` metadata entry.
    pub fn load(det_path: &Path, rec_path: &Path) -> Result<Self> {
        for p in [det_path, rec_path] {
            if !p.exists() {
                return Err(AppError::Config(format!(
                    "OCR model not found: {} (copy ppocr_det.onnx / ppocr_rec.onnx next to the exe)",
                    p.display()
                )));
            }
        }
        Ok(Self {
            det: det::Detector::load(det_path)?,
            rec: rec::Recognizer::load(rec_path)?,
        })
    }

    /// Detect and recognise all text lines in `img`, in reading order
    /// (top-to-bottom, then left-to-right).  Lines scoring below
    /// [`TEXT_SCORE_MIN`] are dropped.
    pub fn recognize(&mut self, img: &DynamicImage) -> Result<Vec<OcrLine>> {
        let boxes = self.det.detect(img)?;
        if boxes.is_empty() {
            return Ok(vec![]);
        }
        let crops: Vec<DynamicImage> = boxes
            .iter()
            .map(|b| img.crop_imm(b.x, b.y, b.w, b.h))
            .collect();
        let lines = self.rec.recognize_batch(&crops)?;
        Ok(lines
            .into_iter()
            .filter(|l| l.score >= TEXT_SCORE_MIN && !l.text.trim().is_empty())
            .collect())
    }

    /// Convenience: all recognised text joined by newlines — what the FTS
    /// index stores per page.
    pub fn recognize_to_text(&mut self, img: &DynamicImage) -> Result<String> {
        let lines = self.recognize(img)?;
        Ok(lines
            .into_iter()
            .map(|l| l.text)
            .collect::<Vec<_>>()
            .join("\n"))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    /// Parity test against the RapidOCR-Python reference output.
    /// Requires models/ppocr_{det,rec}.onnx + ORT_DYLIB_PATH (see the
    /// DINOv2 smoke test for why the dylib path must be explicit):
    /// `__COMPAT_LAYER=RunAsInvoker ORT_DYLIB_PATH=$PWD/onnxruntime.dll \
    ///     cargo test ocr_parity -- --ignored`
    #[test]
    #[ignore = "requires models/ppocr_*.onnx + ORT_DYLIB_PATH"]
    fn ocr_parity_with_rapidocr_reference() {
        let mut engine = OcrEngine::load(
            Path::new("models/ppocr_det.onnx"),
            Path::new("models/ppocr_rec.onnx"),
        )
        .expect("models must load");

        let img = image::open("test_fixtures/ocr_sample.png").expect("fixture");
        let lines = engine.recognize(&img).expect("recognize");
        let all_text: String = lines.iter().map(|l| l.text.as_str()).collect::<Vec<_>>().join("\n");
        println!("recognized:\n{}", all_text);

        let expected: Vec<serde_json::Value> = serde_json::from_str(
            &std::fs::read_to_string("test_fixtures/ocr_sample_expected.json").expect("reference"),
        )
        .expect("reference json");

        // Exact per-line equality is too strict across post-processing
        // variants (our axis-aligned boxes crop slightly differently than
        // RapidOCR's rotated rects).  Require that every reference line's
        // text appears in our output — that's the property the FTS channel
        // depends on.
        for e in &expected {
            let text = e["text"].as_str().unwrap();
            assert!(
                all_text.contains(text),
                "reference line {:?} missing from output:\n{}",
                text,
                all_text
            );
        }
    }
}
